// This file is auto generated by the protocol-buffers cli tool

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var Entry = exports.Entry = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var InflatedEntry = exports.InflatedEntry = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Header = exports.Header = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineEntry()
defineInflatedEntry()
defineHeader()

function defineEntry () {
  var enc = [
    encodings.string,
    encodings.bytes,
    encodings.bool,
    encodings.varint
  ]

  Entry.encodingLength = encodingLength
  Entry.encode = encode
  Entry.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.key)) throw new Error("key is required")
    var len = enc[0].encodingLength(obj.key)
    length += 1 + len
    if (defined(obj.value)) {
      var len = enc[1].encodingLength(obj.value)
      length += 1 + len
    }
    if (defined(obj.deleted)) {
      var len = enc[2].encodingLength(obj.deleted)
      length += 1 + len
    }
    if (!defined(obj.trie)) throw new Error("trie is required")
    var len = enc[1].encodingLength(obj.trie)
    length += 1 + len
    if (defined(obj.clock)) {
      for (var i = 0; i < obj.clock.length; i++) {
        if (!defined(obj.clock[i])) continue
        var len = enc[3].encodingLength(obj.clock[i])
        length += 1 + len
      }
    }
    if (defined(obj.inflate)) {
      var len = enc[3].encodingLength(obj.inflate)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.key)) throw new Error("key is required")
    buf[offset++] = 10
    enc[0].encode(obj.key, buf, offset)
    offset += enc[0].encode.bytes
    if (defined(obj.value)) {
      buf[offset++] = 18
      enc[1].encode(obj.value, buf, offset)
      offset += enc[1].encode.bytes
    }
    if (defined(obj.deleted)) {
      buf[offset++] = 24
      enc[2].encode(obj.deleted, buf, offset)
      offset += enc[2].encode.bytes
    }
    if (!defined(obj.trie)) throw new Error("trie is required")
    buf[offset++] = 34
    enc[1].encode(obj.trie, buf, offset)
    offset += enc[1].encode.bytes
    if (defined(obj.clock)) {
      for (var i = 0; i < obj.clock.length; i++) {
        if (!defined(obj.clock[i])) continue
        buf[offset++] = 40
        enc[3].encode(obj.clock[i], buf, offset)
        offset += enc[3].encode.bytes
      }
    }
    if (defined(obj.inflate)) {
      buf[offset++] = 48
      enc[3].encode(obj.inflate, buf, offset)
      offset += enc[3].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      key: "",
      value: null,
      deleted: false,
      trie: null,
      clock: [],
      inflate: 0
    }
    var found0 = false
    var found3 = false
    while (true) {
      if (end <= offset) {
        if (!found0 || !found3) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.key = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        found0 = true
        break
        case 2:
        obj.value = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        case 3:
        obj.deleted = enc[2].decode(buf, offset)
        offset += enc[2].decode.bytes
        break
        case 4:
        obj.trie = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        found3 = true
        break
        case 5:
        obj.clock.push(enc[3].decode(buf, offset))
        offset += enc[3].decode.bytes
        break
        case 6:
        obj.inflate = enc[3].decode(buf, offset)
        offset += enc[3].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineInflatedEntry () {
  var Feed = InflatedEntry.Feed = {
    buffer: true,
    encodingLength: null,
    encode: null,
    decode: null
  }

  defineFeed()

  function defineFeed () {
    var enc = [
      encodings.bytes
    ]

    Feed.encodingLength = encodingLength
    Feed.encode = encode
    Feed.decode = decode

    function encodingLength (obj) {
      var length = 0
      if (!defined(obj.key)) throw new Error("key is required")
      var len = enc[0].encodingLength(obj.key)
      length += 1 + len
      return length
    }

    function encode (obj, buf, offset) {
      if (!offset) offset = 0
      if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
      var oldOffset = offset
      if (!defined(obj.key)) throw new Error("key is required")
      buf[offset++] = 10
      enc[0].encode(obj.key, buf, offset)
      offset += enc[0].encode.bytes
      encode.bytes = offset - oldOffset
      return buf
    }

    function decode (buf, offset, end) {
      if (!offset) offset = 0
      if (!end) end = buf.length
      if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
      var oldOffset = offset
      var obj = {
        key: null
      }
      var found0 = false
      while (true) {
        if (end <= offset) {
          if (!found0) throw new Error("Decoded message is not valid")
          decode.bytes = offset - oldOffset
          return obj
        }
        var prefix = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tag = prefix >> 3
        switch (tag) {
          case 1:
          obj.key = enc[0].decode(buf, offset)
          offset += enc[0].decode.bytes
          found0 = true
          break
          default:
          offset = skip(prefix & 7, buf, offset)
        }
      }
    }
  }

  var enc = [
    encodings.string,
    encodings.bytes,
    encodings.bool,
    encodings.varint,
    Feed
  ]

  InflatedEntry.encodingLength = encodingLength
  InflatedEntry.encode = encode
  InflatedEntry.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.key)) throw new Error("key is required")
    var len = enc[0].encodingLength(obj.key)
    length += 1 + len
    if (defined(obj.value)) {
      var len = enc[1].encodingLength(obj.value)
      length += 1 + len
    }
    if (defined(obj.deleted)) {
      var len = enc[2].encodingLength(obj.deleted)
      length += 1 + len
    }
    if (!defined(obj.trie)) throw new Error("trie is required")
    var len = enc[1].encodingLength(obj.trie)
    length += 1 + len
    if (defined(obj.clock)) {
      for (var i = 0; i < obj.clock.length; i++) {
        if (!defined(obj.clock[i])) continue
        var len = enc[3].encodingLength(obj.clock[i])
        length += 1 + len
      }
    }
    if (defined(obj.inflate)) {
      var len = enc[3].encodingLength(obj.inflate)
      length += 1 + len
    }
    if (defined(obj.feeds)) {
      for (var i = 0; i < obj.feeds.length; i++) {
        if (!defined(obj.feeds[i])) continue
        var len = enc[4].encodingLength(obj.feeds[i])
        length += varint.encodingLength(len)
        length += 1 + len
      }
    }
    if (defined(obj.contentFeed)) {
      var len = enc[1].encodingLength(obj.contentFeed)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.key)) throw new Error("key is required")
    buf[offset++] = 10
    enc[0].encode(obj.key, buf, offset)
    offset += enc[0].encode.bytes
    if (defined(obj.value)) {
      buf[offset++] = 18
      enc[1].encode(obj.value, buf, offset)
      offset += enc[1].encode.bytes
    }
    if (defined(obj.deleted)) {
      buf[offset++] = 24
      enc[2].encode(obj.deleted, buf, offset)
      offset += enc[2].encode.bytes
    }
    if (!defined(obj.trie)) throw new Error("trie is required")
    buf[offset++] = 34
    enc[1].encode(obj.trie, buf, offset)
    offset += enc[1].encode.bytes
    if (defined(obj.clock)) {
      for (var i = 0; i < obj.clock.length; i++) {
        if (!defined(obj.clock[i])) continue
        buf[offset++] = 40
        enc[3].encode(obj.clock[i], buf, offset)
        offset += enc[3].encode.bytes
      }
    }
    if (defined(obj.inflate)) {
      buf[offset++] = 48
      enc[3].encode(obj.inflate, buf, offset)
      offset += enc[3].encode.bytes
    }
    if (defined(obj.feeds)) {
      for (var i = 0; i < obj.feeds.length; i++) {
        if (!defined(obj.feeds[i])) continue
        buf[offset++] = 58
        varint.encode(enc[4].encodingLength(obj.feeds[i]), buf, offset)
        offset += varint.encode.bytes
        enc[4].encode(obj.feeds[i], buf, offset)
        offset += enc[4].encode.bytes
      }
    }
    if (defined(obj.contentFeed)) {
      buf[offset++] = 66
      enc[1].encode(obj.contentFeed, buf, offset)
      offset += enc[1].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      key: "",
      value: null,
      deleted: false,
      trie: null,
      clock: [],
      inflate: 0,
      feeds: [],
      contentFeed: null
    }
    var found0 = false
    var found3 = false
    while (true) {
      if (end <= offset) {
        if (!found0 || !found3) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.key = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        found0 = true
        break
        case 2:
        obj.value = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        case 3:
        obj.deleted = enc[2].decode(buf, offset)
        offset += enc[2].decode.bytes
        break
        case 4:
        obj.trie = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        found3 = true
        break
        case 5:
        obj.clock.push(enc[3].decode(buf, offset))
        offset += enc[3].decode.bytes
        break
        case 6:
        obj.inflate = enc[3].decode(buf, offset)
        offset += enc[3].decode.bytes
        break
        case 7:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.feeds.push(enc[4].decode(buf, offset, offset + len))
        offset += enc[4].decode.bytes
        break
        case 8:
        obj.contentFeed = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineHeader () {
  var enc = [
    encodings.string
  ]

  Header.encodingLength = encodingLength
  Header.encode = encode
  Header.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.protocol)) throw new Error("protocol is required")
    var len = enc[0].encodingLength(obj.protocol)
    length += 1 + len
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.protocol)) throw new Error("protocol is required")
    buf[offset++] = 10
    enc[0].encode(obj.protocol, buf, offset)
    offset += enc[0].encode.bytes
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      protocol: ""
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.protocol = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        found0 = true
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
